[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[build]
watchPatterns = ["src/**"]

[build]
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "echo starting"

[deploy]
numReplicas = 2

[deploy]
healthcheckPath = "/health"

[deploy]
healthcheckTimeout = 300

[deploy]
restartPolicyType = "never"

[deploy]
restartPolicyMaxRetries = 5

[environments.production.deploy]
startCommand = "echo starting production!"