# Generated by Django 3.2 on 2023-07-17 21:10

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='landImage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='landImage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='last_updated',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='squareImage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='squareImage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tallImage',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='tallImage'),
        ),
    ]
